name: Build & Deploy API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # AWS Auth
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password \
          | docker login --username AWS --password-stdin \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Build & Push Image
      - name: Build and Push API Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cornerstone-worker:latest \
            --push .

      - name: Generate Worker runtime env from SSM
        run: |
          cd cornerstone-infra

          echo "Pulling latest infra changes..."
          git fetch origin
          git reset --hard origin/main

          cp worker.env worker.runtime.env

          aws ssm get-parameters-by-path \
            --path "/cornerstone/common" \
            --with-decryption \
            --query "Parameters[*].[Name,Value]" \
            --output text \
          | sed 's#.*/##' \
          | awk '{print $1"="$2}' >> worker.runtime.env

          aws ssm get-parameters-by-path \
            --path "/cornerstone/worker" \
            --with-decryption \
            --query "Parameters[*].[Name,Value]" \
            --output text \
          | sed 's#.*/##' \
          | awk '{print $1"="$2}' >> worker.runtime.env

      # Deploy on EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd cornerstone-infra

            echo "Pulling latest infra changes..."
            git fetch origin
            git reset --hard origin/main

            echo "Stopping old containers..."
            docker compose down

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting services..."
            docker compose up -d
